// <auto-generated />
using System;
using EasyBurger.API.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyBurger.API.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20220918210540_UserTable")]
    partial class UserTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EasyBurger.API.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5172cb3a-ba03-42e3-aa03-b10410bb3d44"),
                            Description = "Hambúrguer artesanal, queijo, alface americana, tomate, maionese artesanal, bacon e pão de brioche.",
                            ImgUrl = "https://static-images.ifood.com.br/image/upload/t_medium/pratos/381719c4-1633-4690-a9bd-b2937d38b658/202102031326_Iejr_.jpeg",
                            Name = "Cheese bacon",
                            Price = 28.9m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = new Guid("81459d7e-fba4-4a3f-b06c-64c5a0417400"),
                            Description = "2 Deliciosos hambúrgueres artesanais 150g, fatias de Cheddar, fatias de mussarela, bacon, maionese, alface americana, tomate, cebola roxa, molho jack no pão tradicional",
                            ImgUrl = "https://files.menudino.com/cardapios/33262/189.jpg",
                            Name = "Galaxy",
                            Price = 33.60m,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = new Guid("f08209a5-ddb7-4e1f-a629-a2ebd87b71da"),
                            Description = "Delicioso hambúrguer artesanal 140g, fatias de Cheddar, molho de cheddar da casa, bacon, alface americana, tomate, cebola roxa, maionese e molho especial no pão tradicional",
                            ImgUrl = "https://files.menudino.com/cardapios/33262/196.jpg",
                            Name = "Star",
                            Price = 20.90m,
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = new Guid("feb0dee2-9d82-452f-8707-be0782238953"),
                            Description = "Delicioso hambúrguer artesanal 180g, fatia de Cheddar, empanado de 2 queijos (catupiry e provolone) frito, cebola crispy, fatias de cheddar, bacon e maionese no pão tradicional ou pão de brioche",
                            ImgUrl = "https://files.menudino.com/cardapios/33262/188.jpg",
                            Name = "Provolone Crispy",
                            Price = 37.50m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = new Guid("8d51cad6-bca4-4f00-bea6-983c71e9dc66"),
                            Description = "Dois hambúrgueres 120 gr de angus, vinagrete de chimichurri, alface no pão brioche.",
                            ImgUrl = "https://static-images.ifood.com.br/image/upload/t_medium/pratos/a9399dc5-5f22-454a-8895-16c154511760/202004282006_lkS3_b.jpg",
                            Name = "Brutus",
                            Price = 36.00m,
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = new Guid("109a39d8-7f02-4778-b19b-9e0089d225d7"),
                            Description = "Smash de 120g de carne angus, queijo gorgonzola, bacon, geleia de tomate e maionese da casa.",
                            ImgUrl = "https://static-images.ifood.com.br/image/upload/t_medium/pratos/a9399dc5-5f22-454a-8895-16c154511760/202111021436_0G0V_i.jpg",
                            Name = "Relíquia",
                            Price = 32.00m,
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("EasyBurger.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .UseCollation("ascii_general_ci");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
